### ISSUE TITLE
how to use this tool to break down a target compound?(Retrosynthesis)

### ISSUE THREAD

**Issue by ljh433** [otori-bird/retrosynthesis#10]
I have some target compounds(SMILES), but I have no idea how to use your tool to break it down into some reactants.Any help would be appreciated.

**Comment by otori-bird** [comment]
If you simply want to predict potential reactants based on our method, you can refer to the "Environment Preparation" section in the readme document to set up the environment and download the pre-trained model for prediction. 

We may develop a more user-friendly website in the future to provide reactant prediction services.

**Comment by otori-bird** [comment]
Since the questioner has not asked any further questions for a long time, I believe it is appropriate to close this issue.
