### ISSUE TITLE
文章中的canonical SMILES与rdkit中的CanonSmiles不一致

### ISSUE THREAD

**Issue by Jasmine969** [otori-bird/retrosynthesis#3]
![image](https://user-images.githubusercontent.com/64536863/179473936-9f65d8a3-c1cc-4ef9-9ec3-5489bcc42660.png)
我把Figure 1的SMILES用rdkit转化为标准SMILES后发现了不一致的问题，我的rdkit版本也是2020.09.1
![image](https://user-images.githubusercontent.com/64536863/179474345-54530b4c-100c-4e4b-9ba4-01a6a4795ffd.png)
```python
>>>import rdkit
>>>rdkit.__version__
'2020.09.1'
>>>from rdkit import Chem
>>>Chem.CanonSmiles('ClC(Cl)(Cl)COC(=O)C=C')
'C=CC(=O)OCC(Cl)(Cl)Cl'
>>>Chem.CanonSmiles('C=CC(=O)Cl.OCC(Cl)(Cl)Cl')
'C=CC(=O)Cl.OCC(Cl)(Cl)Cl'
```
想问一下作者是如何得到文章Figure 1中的canonical SMILES的？

**Comment by otori-bird** [comment]
十分抱歉，这可能是当时我们制图的错误。

我们获得canonical SMILES的方法也是使用CanonSMILES或clear_map_canonical_smiles函数：
`
def clear_map_canonical_smiles(smi, canonical=True, root=-1):
    mol = Chem.MolFromSmiles(smi)
    if mol is not None:
        for atom in mol.GetAtoms():
            if atom.HasProp('molAtomMapNumber'):
                atom.ClearProp('molAtomMapNumber')
        return Chem.MolToSmiles(mol, isomericSmiles=True, rootedAtAtom=root, canonical=canonical)
    else:
        return smi
`

这两个函数获得的结果都和你的结果是一致的。

这个错误应该只出现在了Figure1，这可能是我们在画图时将它与R-SMILES的数据搞混而导致的。
在对canoncial SMILES数据对的编辑距离重新计算后，和论文中表格的数据是一致的。

十分感谢您指出的错误，我们会在之后的arxiv版本修改这一问题。在正式发表的论文上如果期刊允许我们也会加以修改。

**Comment by Jasmine969** [comment]
好吧，既然您得到的canonical SMILES跟我得出的是一样的话，那么你们在Introduction第三段得出canonical SMILES具有“large input-output discrepancy”以及第四段的“large edit distance between the input SMILES and output SMILES adopted in existing models”是基于什么SMILES呢？因为实际的产物和反应物的canonical SMILES的原子位置是对应起来的，没有出现所谓的“discrepancy”。
比如`'ClC(Cl)(Cl)COC(=O)C=C'`和`'C=CC(=O)Cl.OCC(Cl)(Cl)Cl'`

**Comment by otori-bird** [comment]
> 
”large input-output discrepance“是在canonical SMILES和randomized SMILES都存在的问题。

正如我们在Figure 3展示的一样，对于canonical SMILES而言，是可能存在较多的对齐区间的（如Figure 3中的第一、第二个反应），但这种约束并不是显式的。

在Figure 3中的第三、第四个反应中，对于canonical SMILES而言，他们之间则是存在较大的编辑距离。
``BrCc1ccc(CBr)cc1.FC(F)(F)c1ccc2c(S)ccnc2c1>>FC(F)(F)c1ccc2c(SCc3ccc(CBr)cc3)ccnc2c1`` 
 `CC(C)(C)OC(=O)N1CCNCC1.Cc1ccc(Br)c(F)c1>>Cc1ccc(N2CCN(C(=O)OC(C)(C)C)CC2)c(F)c1`

在Table 2中我们列出了对于数据集中不同类型的SMILES数据对统计后的平均编辑距离，我们认为这些数据的对比是更加具有代表性的。

**Comment by otori-bird** [comment]
There seemed to be no more questions and I decided to close the issue.
