### ISSUE TITLE
generate_RtoP_data.py crashes

### ISSUE THREAD

**Issue by masun** [otori-bird/retrosynthesis#6]
Dears,
I run the the script generate_PtoR.py with my data, everything is ok, but when I run the generate_RtoP_data.py script with the same data, it crushes in this line: **map_number = reactant_candidates[0][0]**

I have printed out the reactant_candidates values and it is very strange that even this list is empty, it does not crash, but other times, yes it crashes and yields the below message.
I have got the same problem using either Linux or Windows. Please, help.
Thank you, best
########################################################
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/miniconda3/miniconda3/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/miniconda3/miniconda3/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "preprocessing/generate_RtoP_data.py", line 453, in multi_process
    map_number = reactant_candidates[0][0]
IndexError: list index out of range
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "preprocessing/generate_RtoP_data.py", line 611, in <module>
    src_data, tgt_data = preprocess(
  File "preprocessing/generate_RtoP_data.py", line 315, in preprocess
    results = pool.map(func=multi_process,iterable=data)
  File "/gpfs1/data/chembiom/tools/miniconda3/miniconda3/lib/python3.8/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/gpfs1/data/chembiom/tools/miniconda3/miniconda3/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
IndexError: list index out of range

**Comment by otori-bird** [comment]
I suspect that the error is caused by the failure of extracting reactants that share the same atom mapping number with the product.  could you share some failure examples?

**Comment by masun** [comment]
Dir Otori,
Here I am sending the reactions taken from KEGG. Please note that the reactant_candidates list for the three of them is empty, but the script does not crash always. Thank you for your help. Best

**reaction_ID,reactants>reagents>production**
**R10954**,[CH3:1][O:2][C:3](=[O:4])[c:5]1[c:6]([OH:7])[cH:8][c:9]2[cH:10][c:11]3[c:12]([c:13]([OH:14])[c:15]2[c:16]1[CH3:17])[C:18](=[O:19])[c:20]1[c:22]([OH:21])[cH:24][c:25]([O:26][CH3:27])[cH:28][c:30]1[C:32]3=[O:33].[NH2:34][C:35](=[O:36])[C:37]1=[CH:81][N:41]([C@@H:42]2[O:43][C@H:44]([CH2:45][O:46][P:47](=[O:48])([OH:49])[O:50][P:51](=[O:52])([OH:53])[O:54][CH2:55][C@H:56]3[O:57][C@@H:58]([n:59]4[cH:60][n:61][c:62]5[c:63]([NH2:64])[n:65][cH:66][n:67][c:68]45)[C@H:69]([O:70][P:71](=[O:72])([OH:73])[OH:74])[C@@H:75]3[OH:76])[C@@H:77]([OH:78])[C@H:79]2[OH:80])[CH:40]=[CH:39][CH2:38]1.[OH2:31].[O:23]=[O:29].[H+]>>[CH3:1][O:2][C:3](=[O:4])[c:5]1[c:6]([OH:7])[cH:8][c:9]2[cH:10][c:11]3[c:12]([c:13]([OH:14])[c:15]2[c:16]1[CH3:17])[C:18](=[O:19])[C@:20]1([OH:21])[C:22](=[O:23])[CH:24]=[C:25]([O:26][CH3:27])[C@@H:28]([OH:29])[C@:30]1([OH:31])[C:32]3=[O:33].[NH2:34][C:35](=[O:36])[c:37]1[cH:38][cH:39][cH:40][n+:41]([C@@H:42]2[O:43][C@H:44]([CH2:45][O:46][P:47](=[O:48])([OH:49])[O:50][P:51](=[O:52])([OH:53])[O:54][CH2:55][C@H:56]3[O:57][C@@H:58]([n:59]4[cH:60][n:61][c:62]5[c:63]([NH2:64])[n:65][cH:66][n:67][c:68]45)[C@H:69]([O:70][P:71](=[O:72])([OH:73])[OH:74])[C@@H:75]3[OH:76])[C@@H:77]([OH:78])[C@H:79]2[OH:80])[cH:81]1.[OH2:82]
**R09281**,[NH2:1][C:2](=[O:3])[c:4]1[cH:5][n+:6]([C@@H:7]2[O:8][C@H:9]([CH2:10][O:11][P:12](=[O:13])([OH:14])[O:15][P:16](=[O:17])([OH:18])[O:19][CH2:20][C@H:21]3[O:22][C@@H:23]([n:24]4[cH:25][n:26][c:27]5[c:28]([NH2:29])[n:30][cH:31][n:32][c:33]45)[C@H:34]([O:35][P:36](=[O:37])([OH:38])[OH:39])[C@@H:40]3[OH:41])[C@@H:42]([OH:43])[C@H:44]2[OH:45])[cH:46][cH:47][cH:48]1.[OH:49][CH2:50][CH2:51][CH2:52][C:53](=[O:54])[OH:55]>>[NH2:1][C:2](=[O:3])[C:4]1=[CH:5][N:6]([C@@H:7]2[O:8][C@H:9]([CH2:10][O:11][P:12](=[O:13])([OH:14])[O:15][P:16](=[O:17])([OH:18])[O:19][CH2:20][C@H:21]3[O:22][C@@H:23]([n:24]4[cH:25][n:26][c:27]5[c:28]([NH2:29])[n:30][cH:31][n:32][c:33]45)[C@H:34]([O:35][P:36](=[O:37])([OH:38])[OH:39])[C@@H:40]3[OH:41])[C@@H:42]([OH:43])[C@H:44]2[OH:45])[CH:46]=[CH:47][CH2:48]1.[O:49]=[CH:50][CH2:51][CH2:52][C:53](=[O:54])[OH:55].[H+:56]
**R09289**,[NH2:1][C:2](=[O:3])[c:4]1[cH:5][n+:6]([C@@H:7]2[O:8][C@H:9]([CH2:10][O:11][P:12](=[O:13])([OH:14])[O:15][P:16](=[O:17])([OH:18])[O:19][CH2:20][C@H:21]3[O:22][C@@H:23]([n:24]4[cH:25][n:26][c:27]5[c:28]([NH2:29])[n:30][cH:31][n:32][c:33]45)[C@H:34]([O:35][P:36](=[O:37])([OH:38])[OH:39])[C@@H:40]3[OH:41])[C@@H:42]([OH:43])[C@H:44]2[OH:45])[cH:46][cH:47][cH:48]1.[OH:49][CH2:50][CH2:51][C:52](=[O:53])[OH:54]>>[NH2:1][C:2](=[O:3])[C:4]1=[CH:5][N:6]([C@@H:7]2[O:8][C@H:9]([CH2:10][O:11][P:12](=[O:13])([OH:14])[O:15][P:16](=[O:17])([OH:18])[O:19][CH2:20][C@H:21]3[O:22][C@@H:23]([n:24]4[cH:25][n:26][c:27]5[c:28]([NH2:29])[n:30][cH:31][n:32][c:33]45)[C@H:34]([O:35][P:36](=[O:37])([OH:38])[OH:39])[C@@H:40]3[OH:41])[C@@H:42]([OH:43])[C@H:44]2[OH:45])[CH:46]=[CH:47][CH2:48]1.[O:49]=[CH:50][CH2:51][C:52](=[O:53])[OH:54].[H+:55]

**Comment by otori-bird** [comment]
> Dir Otori, Here I am sending the reactions taken from KEGG. Please note that the reactant_candidates list for the three of them is empty, but the script does not crash always. Thank you for your help. Best
> 
> **reaction_ID,reactants>reagents>production** **R10954**,[CH3:1][O:2]C:3[c:5]1c:6[cH:8][c:9]2[cH:10][c:11]3c:12C:18[c:20]1c:22[cH:24]c:25[cH:28][c:30]1[C:32]3=[O:33].[NH2:34]C:35[C:37]1=[CH:81]N:41[CH:40]=[CH:39][CH2:38]1.[OH2:31].[O:23]=[O:29].[H+]>>[CH3:1][O:2]C:3[c:5]1c:6[cH:8][c:9]2[cH:10][c:11]3c:12C:18[C@:20]1([OH:21])C:22[CH:24]=C:25C@@h:28[C@:30]1([OH:31])[C:32]3=[O:33].[NH2:34]C:35[c:37]1[cH:38][cH:39][cH:40]n+:41[cH:81]1.[OH2:82] **R09281**,[NH2:1]C:2[c:4]1[cH:5]n+:6[cH:46][cH:47][cH:48]1.[OH:49][CH2:50][CH2:51][CH2:52]C:53[OH:55]>>[NH2:1]C:2[C:4]1=[CH:5]N:6[CH:46]=[CH:47][CH2:48]1.[O:49]=[CH:50][CH2:51][CH2:52]C:53[OH:55].[H+:56] **R09289**,[NH2:1]C:2[c:4]1[cH:5]n+:6[cH:46][cH:47][cH:48]1.[OH:49][CH2:50][CH2:51]C:52[OH:54]>>[NH2:1]C:2[C:4]1=[CH:5]N:6[CH:46]=[CH:47][CH2:48]1.[O:49]=[CH:50][CH2:51]C:52[OH:54].[H+:55]

Thanks for you examples, but the rdkit seems to be unable to recognize the reaction SMILES you provided.

I ran the script below and got some rdkit errors:
```python
from rdkit import Chem
rxn = "[NH2:1]C:2[c:4]1[cH:5]n+:6[cH:46][cH:47][cH:48]1.[OH:49][CH2:50][CH2:51]C:52[OH:54]>>[NH2:1]C:2[C:4]1=[CH:5]N:6[CH:46]=[CH:47][CH2:48]1.[O:49]=[CH:50][CH2:51]C:52[OH:54].[H+:55]"
r, p = rxn.split(">>")
pmol = Chem.MolFromSmiles(p)
```
The error message was: `SMILES Parse Error: unclosed ring for input: '[NH2:1]C:2[C:4]1=[CH:5]N:6[CH:46]=[CH:47][CH2:48]1.[O:49]=[CH:50][CH2:51]C:52[OH:54].[H+:55]`

Could you please check the validity of these examples or provide me with other examples?

**Comment by masun** [comment]
Dear Otori,
Yes you are right. Some SMILEs became invalid after applying RXNMapper tool. It is recommended to use Indigo.  Thank you very much
