### ISSUE TITLE
Are the test sets for USPTO-MIT and USPTO-FULL datasets same as in the baselines?

### ISSUE THREAD

**Issue by mikolajsacha** [otori-bird/retrosynthesis#7]
Hi!
Awesome work and really good results!
I noticed you use a different preprocessing procedure than some of the compared works for USPTO-MIT and USPTO-FULL datasets. For example, USPTO-MIT in the LocalRetro paper has 479 035 reactions, while in your work, it has 482 132 reactions. Similarly, USPTO-FULL in the GLN paper has 1 013 118 reactions, while in your work, it has 960 198 reactions. 

My question is, does this preprocessing also affect the test set on which you evaluate your method? Namely: is the evaluation set exactly the same as in the compared methods? If not, the results might be a bit skewed.

**Comment by otori-bird** [comment]
Nice question. The preprocessing is a little different compared to the works you mentioned.

Just like the Augmented Transformer did, we add a extra procedure to remove invalid reactions that contain
no products or just a single ion as reactants, and it also affect the test set. You can find this preprocessing procedure in our paper and code both. The proportion of this kind of reactions is about 4% in USPTO-FULL.  

The accuracies can be recalculated for the test set by assuming that our model failed for all 4% of excluded reactions, which may lead to about 2% decrease of top-1 accuracy. 

And its sorry that it's not clear to me why LocalRetro has more data than ours.

**Comment by mikolajsacha** [comment]
Thank you for your response! I work on retrosynthesis models and noticed, by reading different papers and code, that there are many different data preprocessing, and even accuracy comparison methods, used in different publications. This makes me suspicious of the exact Top K scores that are reported. I think this issue is something that is worth working on for the community.
